### ISSUE TITLE
[Issue] Crash on game initialization

### ISSUE THREAD

**Issue by accessdenied0** [TeamMetallurgy/MetallurgyClassicMachines#4]
Dear @Glassmaker / @Shadowclaimer,

I don't what I have to say: I have no idea why it crashes, I only know when: On game initialization. http://pastebin.com/xbVjEHWZ

I'm sorry

access_denied

**Comment by Glassmaker** [comment]
Hi @accessdenied0 
Well, that is the first time seeing that one o.o

In the config there are two log settings (B:invaild_log, and B:verbose_log) under abstractor -> general, can you kindly turn them on, and upload your fml-client-latest.log.

Don't worry, things happen :)

**Comment by accessdenied0** [comment]
Hey @Glassmaker ,

Thank you a lot for your help,

Here it is: https://drive.google.com/file/d/0B1BMWHu8n1hXei1XS0xmTFJoNWM/view?usp=sharing

and also the client crash-log if needed: http://pastebin.com/1cpA23Dw

I hope this helps,

access_denied

**Comment by Glassmaker** [comment]
Hi @accessdenied0 
I couldn't recreate the crash.

Although, I added code to prevent that crash.

so, here is a build to test

http://www.mediafire.com/download/5p5y019gs1vu0os/MetallurgyClassicMachines-1.7.10-0.1.0.61.jar

Let me know if the build fixes the issue for you :)

**Comment by accessdenied0** [comment]
Hey @Glassmaker,

Thank you a lot! This seem to work now (Minecraft starts, World loads, World works...)! I still have to test every single machine, but I'm optimistic.

Thank you very much for all your efforts :) ,

access_denied

**Comment by Glassmaker** [comment]
You're welcome :)
Closing this issue :)
