### ISSUE TITLE
Furnaces use Crushers' Fuel Efficiency 

### ISSUE THREAD

**Issue by thor12022** [TeamMetallurgy/MetallurgyClassicMachines#6]
The metal furnaces seem to be using the Crusher's Fuel Efficiency.
Changing the Furnaces' Fuel Efficiency in the config has no effect, but changing the Crushers' Fuel Efficiency values also affects the corresponding Furnace.

[Here.](https://github.com/TeamMetallurgy/MetallurgyClassicMachines/blob/master/src/main/java/com/teammetallurgy/metallurgycm/tileentity/TileEntityMetalFurnace.java#L42)

**Comment by Glassmaker** [comment]
Guess I missed that though testing, will be fixed :)
